apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local: 
    push: false
  artifacts:
    - image: kapbyte/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: kapbyte/tickets
      context: tickets 
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: kapbyte/orders
      context: orders 
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: kapbyte/expiration
      context: expiration 
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: kapbyte/payments
      context: payments 
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .